#ifndef BPNN_EXAMPLE_CONFIG_H
#define BPNN_EXAMPLE_CONFIG_H

#define INPUT_IMAGE_SIZE  28
#define INPUT_LAYER_SIZE  (INPUT_IMAGE_SIZE * INPUT_IMAGE_SIZE)
#define HIDE_LAYER_SIZE   128
#define OUTPUT_LAYER_SIZE 10

#endif // !BPNN_EXAMPLE_CONFIG_H
